# Generated by Django 3.1.5 on 2021-04-05 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=10000, unique=True)),
                ('location', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField(default='')),
                ('specialization', models.CharField(max_length=500)),
                ('owned', models.CharField(choices=[('C', 'Central University'), ('D', 'Deemed University'), ('P', 'Private University')], default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('CS', 'College Student'), ('F', 'Faculty'), ('CAS', 'College Aspirant'), ('O', 'Others')], max_length=50)),
                ('college', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, default='', max_length=500)),
                ('question', models.CharField(blank=True, default='', max_length=500)),
                ('time', models.DateTimeField(default='')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
