# Generated by Django 3.1.5 on 2021-04-05 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CB', '0002_auto_20210405_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=500)),
                ('time', models.DateTimeField(default='')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, default='', max_length=500)),
                ('time', models.DateTimeField(default='')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CollegeInfo',
        ),
    ]
