# Generated by Django 3.1.5 on 2021-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB', '0003_auto_20210405_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegequestion',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='collegereview',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
