# Generated by Django 3.1.5 on 2021-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CB', '0004_auto_20210405_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegequestion',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
