# Generated by Django 3.1.5 on 2021-04-30 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CB', '0005_collegequestion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegequestion',
            name='answer',
        ),
        migrations.AlterField(
            model_name='collegequestion',
            name='question',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
        migrations.CreateModel(
            name='QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(blank=True, default='', max_length=1000)),
                ('time', models.DateTimeField(default='')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.collegequestion', to_field='question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
