# Generated by Django 3.1.5 on 2021-04-30 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CB', '0007_remove_questionanswers_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswers',
            name='college',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name'),
            preserve_default=False,
        ),
    ]
