# Generated by Django 3.1.5 on 2021-05-14 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CB', '0008_questionanswers_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followcollege',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CB.college', to_field='college_name', unique=True),
        ),
    ]
